package com.example.arangkada.activities;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.view.GravityCompat;
import androidx.drawerlayout.widget.DrawerLayout;

import com.example.arangkada.R;
import com.google.android.material.navigation.NavigationView;
import com.google.firebase.auth.FirebaseAuth;

public abstract class BaseActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener {

    protected DrawerLayout drawerLayout;
    protected NavigationView navigationView;
    protected ImageView menuButton;
    protected ImageView backButton;
    protected LinearLayout navigationContainer;

    private FirebaseAuth mAuth;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mAuth = FirebaseAuth.getInstance();
    }

    protected void setupNavigation() {
        drawerLayout = findViewById(R.id.drawer_layout);
        navigationView = findViewById(R.id.nav_view);
        menuButton = findViewById(R.id.btn_menu);
        backButton = findViewById(R.id.btn_back);
        navigationContainer = findViewById(R.id.navigation_container);

        if (navigationView != null) {
            navigationView.setNavigationItemSelectedListener(this);
        }

        if (menuButton != null) {
            menuButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (drawerLayout != null) {
                        drawerLayout.openDrawer(GravityCompat.END);
                    }
                }
            });
        }

        if (backButton != null) {
            backButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    onBackPressed();
                }
            });
        }
    }

    protected void showBackButton() {
        if (backButton != null && menuButton != null) {
            backButton.setVisibility(View.VISIBLE);
            menuButton.setVisibility(View.GONE);
        }
    }

    protected void showMenuButton() {
        if (backButton != null && menuButton != null) {
            backButton.setVisibility(View.GONE);
            menuButton.setVisibility(View.VISIBLE);
        }
    }

    // helper
    protected void setToolbarTitle(String title) {
        TextView toolbarTitle = findViewById(R.id.toolbar_title);
        if (toolbarTitle != null) {
            toolbarTitle.setText(title);
        }
    }

    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.nav_notifications) {
            openNotifications();
        } else if (id == R.id.nav_language) {
            openLanguageSettings();
        } else if (id == R.id.nav_terms) {
            openTermsAndConditions();
        } else if (id == R.id.nav_delete_account) {
            openAccountDeletion();
        } else if (id == R.id.nav_logout) {
            performLogout();
        }

        if (drawerLayout != null) {
            drawerLayout.closeDrawer(GravityCompat.END);
        }
        return true;
    }

    private void openNotifications() {
        Toast.makeText(this, "This feature is coming soon!", Toast.LENGTH_SHORT).show();

    }

    private void openLanguageSettings() {
        Toast.makeText(this, "Language Settings: English/Filipino - Coming soon!", Toast.LENGTH_SHORT).show();
    }

    private void openTermsAndConditions() {
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setTitle("Terms and Conditions");

        // Create a scrollable TextView
        TextView message = new TextView(this);
        message.setPadding(50, 30, 50, 30);
        message.setTextSize(14f);
        message.setTextColor(getResources().getColor(android.R.color.black));
        message.setText(
                "This agreement contains the terms and conditions (hereinafter, the “Terms and Conditions”) that govern access and use of the mobile application (ARANGKADA) that are either referenced or linked to the Terms and Conditions.\n\n" +
                        "Any individual who wishes to access or use the mobile application may do so subject to the Terms and Conditions. Anyone who does not accept the Terms and Conditions, which are binding and mandatory, should refrain from using the mobile application.\n\n" +
                        "These Terms and Conditions represent a data message as defined in RA 8792 (E-Commerce Act). Such data messages are generated by a computer system and do not require any physical or digital signature.\n\n" +
                        "Definitions:\n\n" +
                        "Transportation Contract: This refers to the agreement between the User and the Van Operator for the provision of van transportation services, established upon successful reservation.\n\n" +
                        "Payment Facilities: Payment is required upon confirmation of reservation through the application or directly at the terminal, depending on the setup of the Van Operator.\n\n" +
                        "Van Operator: The company or authorized individual responsible for providing van services. This operator is recognized by law to transport passengers and is a party to the Transportation Contract with the User.\n\n" +
                        "Fare/Ticket: This is the official travel document issued by the Van Operator upon confirmed reservation. It includes trip details and proof of payment. The app allows the User to view upcoming and previous reservations.\n\n" +
                        "Person: This may refer to an individual, organization, association, government unit, or other entity utilizing the Arangkada system to make a reservation or enter a contract with the Van Operator.\n\n" +
                        "Transaction: The process carried out via the mobile application to secure a reservation or complete a payment, whether digitally or physically at the terminal, in compliance with the Transportation Contract.\n\n" +
                        "User: Any individual who makes a reservation or performs any transaction using the Arangkada mobile application."
        );

        // Make it scrollable
        final ScrollView scrollView = new ScrollView(this);
        scrollView.addView(message);

        builder.setView(scrollView);

        builder.setPositiveButton("OK", (dialog, which) -> dialog.dismiss());

        AlertDialog dialog = builder.create();
        dialog.show();
    }


    private void openAccountDeletion() {
        Toast.makeText(this, "Account Deletion - Feature coming soon!", Toast.LENGTH_SHORT).show();
    }

    private void performLogout() {
        if (mAuth != null) {
            mAuth.signOut();
        }

        Toast.makeText(this, "Logging out...", Toast.LENGTH_SHORT).show();

        Intent intent = new Intent(this, AuthActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        startActivity(intent);
        overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out);
        finish();
    }

    @Override
    public void onBackPressed() {
        if (drawerLayout != null && drawerLayout.isDrawerOpen(GravityCompat.END)) {
            drawerLayout.closeDrawer(GravityCompat.END);
        } else {
            super.onBackPressed();
        }
    }


    protected abstract void onNavigationSetup();
}
